const SYSTEM_MASTER_RULES = {
  systemName: 'Nokta Academy Management System',
  generatedAt: '2026-04-16T00:00:00.000Z',
  roles: [
    { key: 'SUPER_ADMIN', slug: 'super_admin', scope: 'global', description: 'Full enterprise control across the platform.' },
    { key: 'ADMIN', slug: 'admin', scope: 'operational', description: 'Operational academy administration access.' },
    { key: 'TEACHER', slug: 'teacher', scope: 'instructional', description: 'Teacher access limited to assigned academic areas.' },
    { key: 'STUDENT', slug: 'student', scope: 'self', description: 'Student self-service access.' },
    { key: 'PARENT', slug: 'parent', scope: 'linked-family', description: 'Read-only linked child access.' },
    { key: 'OWNER', slug: 'owner', scope: 'governance', description: 'Policy and analytics governance access.' },
    { key: 'BRANCH_MANAGER', slug: 'branch_manager', scope: 'branch', description: 'Branch-scoped operational management.' },
    { key: 'SYSTEM_AUTOMATION', slug: 'system_automation', scope: 'service', description: 'Internal automation and jobs role.' }
  ],
  legacyRoleAliases: {
    family_student: 'parent',
    family: 'parent',
    accountant: 'admin',
    librarian: 'branch_manager',
    user: 'student'
  },
  permissions: [
    'DASHBOARD_VIEW',
    'USER_CREATE',
    'USER_VIEW',
    'USER_UPDATE',
    'USER_ACTIVATE',
    'USER_DEACTIVATE',
    'USER_DELETE',
    'ROLE_VIEW',
    'ROLE_MANAGE',
    'PERMISSION_VIEW',
    'PERMISSION_MANAGE',
    'BRANCH_CREATE',
    'BRANCH_VIEW',
    'BRANCH_UPDATE',
    'BRANCH_DELETE_REQUEST',
    'BRANCH_DELETE_APPROVE',
    'STUDENT_REGISTER',
    'STUDENT_VIEW',
    'STUDENT_UPDATE',
    'STUDENT_ASSIGN_CLASS',
    'STUDENT_SUSPEND',
    'TEACHER_REGISTER',
    'TEACHER_VIEW',
    'TEACHER_UPDATE',
    'TEACHER_ASSIGN_SUBJECT',
    'TEACHER_ASSIGN_CLASS',
    'TEACHER_PAYROLL_VIEW',
    'CLASS_CREATE',
    'CLASS_VIEW',
    'CLASS_UPDATE',
    'CLASS_DELETE',
    'SUBJECT_CREATE',
    'SUBJECT_VIEW',
    'SUBJECT_UPDATE',
    'ENROLLMENT_CREATE',
    'ENROLLMENT_VIEW',
    'ENROLLMENT_UPDATE',
    'ATTENDANCE_MARK',
    'ATTENDANCE_VIEW',
    'ATTENDANCE_POLICY_UPDATE',
    'EXAM_CREATE',
    'EXAM_VIEW',
    'EXAM_UPDATE',
    'EXAM_GRADE',
    'EXAM_PUBLISH',
    'QUESTION_CREATE',
    'QUESTION_VIEW',
    'QUESTION_UPDATE',
    'RESULT_CREATE',
    'RESULT_VIEW',
    'RESULT_PUBLISH',
    'PAYMENT_CREATE',
    'PAYMENT_VIEW',
    'PAYMENT_AUDIT',
    'SALARY_VIEW',
    'SALARY_MANAGE',
    'SALARY_AUDIT',
    'EXPENSE_CREATE',
    'EXPENSE_VIEW',
    'EXPENSE_AUDIT',
    'STATIONERY_SALE_CREATE',
    'STATIONERY_SALE_VIEW',
    'ANNOUNCEMENT_CREATE',
    'ANNOUNCEMENT_VIEW',
    'NOTIFICATION_CREATE',
    'NOTIFICATION_VIEW',
    'ADVERTISEMENT_CREATE',
    'ADVERTISEMENT_VIEW',
    'RESOURCE_CREATE',
    'RESOURCE_VIEW',
    'RESOURCE_UPDATE',
    'FAMILY_LINK_CREATE',
    'FAMILY_LINK_VIEW',
    'QR_CONTACT_CREATE',
    'QR_CONTACT_VIEW',
    'SESSION_VIEW',
    'SESSION_MANAGE',
    'REPORT_VIEW',
    'REPORT_EXPORT',
    'REPORT_GENERATE',
    'LANGUAGE_SETTING_UPDATE',
    'POLICY_UPDATE',
    'SYSTEM_RULE_UPDATE',
    'AUDIT_VIEW'
  ],
  permissionMatrix: {
    super_admin: ['*'],
    admin: ['DASHBOARD_VIEW', 'USER_VIEW', 'USER_UPDATE', 'USER_ACTIVATE', 'STUDENT_REGISTER', 'STUDENT_VIEW', 'STUDENT_UPDATE', 'STUDENT_ASSIGN_CLASS', 'STUDENT_SUSPEND', 'TEACHER_REGISTER', 'TEACHER_VIEW', 'TEACHER_UPDATE', 'TEACHER_ASSIGN_SUBJECT', 'TEACHER_ASSIGN_CLASS', 'CLASS_CREATE', 'CLASS_VIEW', 'CLASS_UPDATE', 'SUBJECT_CREATE', 'SUBJECT_VIEW', 'SUBJECT_UPDATE', 'ENROLLMENT_CREATE', 'ENROLLMENT_VIEW', 'ENROLLMENT_UPDATE', 'ATTENDANCE_MARK', 'ATTENDANCE_VIEW', 'ATTENDANCE_POLICY_UPDATE', 'EXAM_CREATE', 'EXAM_VIEW', 'EXAM_UPDATE', 'EXAM_GRADE', 'EXAM_PUBLISH', 'QUESTION_CREATE', 'QUESTION_VIEW', 'QUESTION_UPDATE', 'RESULT_CREATE', 'RESULT_VIEW', 'RESULT_PUBLISH', 'PAYMENT_CREATE', 'PAYMENT_VIEW', 'SALARY_VIEW', 'EXPENSE_CREATE', 'EXPENSE_VIEW', 'STATIONERY_SALE_CREATE', 'STATIONERY_SALE_VIEW', 'ANNOUNCEMENT_CREATE', 'ANNOUNCEMENT_VIEW', 'NOTIFICATION_CREATE', 'NOTIFICATION_VIEW', 'RESOURCE_CREATE', 'RESOURCE_VIEW', 'RESOURCE_UPDATE', 'FAMILY_LINK_CREATE', 'FAMILY_LINK_VIEW', 'QR_CONTACT_CREATE', 'QR_CONTACT_VIEW', 'REPORT_VIEW', 'REPORT_EXPORT', 'LANGUAGE_SETTING_UPDATE'],
    teacher: ['DASHBOARD_VIEW', 'STUDENT_VIEW', 'CLASS_VIEW', 'SUBJECT_VIEW', 'ATTENDANCE_MARK', 'ATTENDANCE_VIEW', 'EXAM_CREATE', 'EXAM_VIEW', 'EXAM_UPDATE', 'EXAM_GRADE', 'QUESTION_CREATE', 'QUESTION_VIEW', 'QUESTION_UPDATE', 'RESULT_CREATE', 'RESULT_VIEW', 'ANNOUNCEMENT_VIEW', 'NOTIFICATION_CREATE', 'NOTIFICATION_VIEW', 'RESOURCE_VIEW', 'RESOURCE_UPDATE', 'FAMILY_LINK_VIEW'],
    student: ['DASHBOARD_VIEW', 'ATTENDANCE_VIEW', 'EXAM_VIEW', 'RESULT_VIEW', 'PAYMENT_VIEW', 'ANNOUNCEMENT_VIEW', 'NOTIFICATION_VIEW', 'RESOURCE_VIEW', 'QR_CONTACT_VIEW'],
    parent: ['DASHBOARD_VIEW', 'ATTENDANCE_VIEW', 'EXAM_VIEW', 'RESULT_VIEW', 'PAYMENT_VIEW', 'ANNOUNCEMENT_VIEW', 'NOTIFICATION_VIEW', 'RESOURCE_VIEW', 'FAMILY_LINK_VIEW', 'QR_CONTACT_VIEW'],
    owner: ['DASHBOARD_VIEW', 'BRANCH_VIEW', 'PAYMENT_VIEW', 'PAYMENT_AUDIT', 'SALARY_VIEW', 'SALARY_AUDIT', 'EXPENSE_VIEW', 'EXPENSE_AUDIT', 'REPORT_VIEW', 'REPORT_EXPORT', 'POLICY_UPDATE', 'SYSTEM_RULE_UPDATE', 'AUDIT_VIEW', 'SESSION_VIEW'],
    branch_manager: ['DASHBOARD_VIEW', 'BRANCH_VIEW', 'BRANCH_UPDATE', 'USER_VIEW', 'STUDENT_REGISTER', 'STUDENT_VIEW', 'STUDENT_UPDATE', 'STUDENT_ASSIGN_CLASS', 'TEACHER_REGISTER', 'TEACHER_VIEW', 'TEACHER_UPDATE', 'TEACHER_ASSIGN_SUBJECT', 'TEACHER_ASSIGN_CLASS', 'CLASS_CREATE', 'CLASS_VIEW', 'CLASS_UPDATE', 'SUBJECT_CREATE', 'SUBJECT_VIEW', 'SUBJECT_UPDATE', 'ENROLLMENT_CREATE', 'ENROLLMENT_VIEW', 'ENROLLMENT_UPDATE', 'ATTENDANCE_MARK', 'ATTENDANCE_VIEW', 'EXAM_CREATE', 'EXAM_VIEW', 'EXAM_UPDATE', 'EXAM_GRADE', 'RESULT_CREATE', 'RESULT_VIEW', 'PAYMENT_CREATE', 'PAYMENT_VIEW', 'EXPENSE_CREATE', 'EXPENSE_VIEW', 'ANNOUNCEMENT_CREATE', 'ANNOUNCEMENT_VIEW', 'NOTIFICATION_CREATE', 'NOTIFICATION_VIEW', 'RESOURCE_CREATE', 'RESOURCE_VIEW', 'RESOURCE_UPDATE', 'REPORT_VIEW'],
    system_automation: ['ATTENDANCE_MARK', 'ATTENDANCE_VIEW', 'NOTIFICATION_CREATE', 'REPORT_GENERATE', 'SALARY_MANAGE', 'PAYMENT_AUDIT', 'EXPENSE_AUDIT', 'SYSTEM_RULE_UPDATE', 'AUDIT_VIEW']
  },
  businessRules: {
    genderClassAlignment: ['male_student_requires_male_class', 'female_student_requires_female_class', 'teacher_gender_must_match_class_policy'],
    finance: ['payment_records_are_immutable_after_posting', 'exam_results_are_immutable_after_publish', 'financial_records_cannot_be_deleted', 'financial_updates_require_reason_and_audit_history', 'teacher_absence_deduction_afn_50_per_absence'],
    attendance: ['attendance_duplicate_prevention_per_student_per_day_per_session', 'online_attendance_auto_mark_supported', 'automatic_student_suspension_when_policy_threshold_exceeded'],
    governance: ['branch_delete_requires_owner_approval', 'teacher_has_no_salary_edit_access', 'teacher_has_no_branch_access', 'parent_is_read_only_to_linked_children', 'owner_has_policy_and_analytics_access_without_daily_operations'],
    reminders: ['monthly_registration_reminders', 'registration_expiry_reminder_three_days_before_due_date']
  },
  apiMap: {
    system: ['/health', '/'],
    auth: ['/api/auth/login', '/api/auth/refresh', '/api/auth/logout', '/api/auth/profile'],
    users: ['/api/users'],
    students: ['/api/students'],
    teachers: ['/api/teachers'],
    branches: ['/api/branches'],
    classes: ['/api/classes'],
    subjects: ['/api/subjects'],
    enrollments: ['/api/enrollments'],
    attendance: ['/api/attendance', '/api/attendance/policies'],
    exams: ['/api/exams'],
    results: ['/api/results'],
    payments: ['/api/payments'],
    salaries: ['/api/salaries'],
    expenses: ['/api/expenses'],
    finance: ['/api/finance'],
    announcements: ['/api/announcements'],
    notifications: ['/api/notifications'],
    reports: ['/api/reports'],
    resources: ['/api/learning-resources'],
    advertisements: ['/api/advertisements'],
    sessions: ['/api/sessions'],
    audit: ['/api/audit'],
    roles: ['/api/roles'],
    permissions: ['/api/permissions'],
    dashboard: ['/api/dashboard'],
    languageSettings: ['/api/language-settings']
  },
  routeOwnership: [
    { prefix: '/api/auth/profile', ownership: 'self' },
    { prefix: '/api/students', ownership: 'branch_or_self' },
    { prefix: '/api/teachers', ownership: 'branch_or_self' },
    { prefix: '/api/classes', ownership: 'assigned_or_branch' },
    { prefix: '/api/attendance', ownership: 'assigned_or_self' },
    { prefix: '/api/results', ownership: 'assigned_or_self' },
    { prefix: '/api/payments', ownership: 'branch_or_self' },
    { prefix: '/api/reports', ownership: 'governance' }
  ],
  systemDependencies: {
    backend: ['node.js', 'express', 'mongodb', 'mongoose', 'jsonwebtoken', 'bcryptjs', 'joi'],
    frontend: ['react', 'vite', 'tailwindcss', 'react-query', 'zustand', 'i18next', 'framer-motion', 'recharts'],
    security: ['helmet', 'cors', 'express-rate-limit', 'jwt_access_tokens', 'refresh_rotation', 'audit_logging'],
    operational: ['offline-ready-pwa', 'multilingual-support', 'scheduled-jobs', 'soft-delete', 'device-tracking']
  }
};

module.exports = SYSTEM_MASTER_RULES;
module.exports.SYSTEM_MASTER_RULES = SYSTEM_MASTER_RULES;
