import { Router } from 'express';
import adminRouter from '../modules/admin/admin.routes';
import { attendanceRouter } from '../modules/attendance/attendance.routes';
import { auditRouter } from '../modules/audit/audit.routes';
import { authRouter } from '../modules/auth/auth.routes';
import { bookRouter } from '../modules/books/books.routes';
import { branchRouter } from '../modules/branches/branches.routes';
import { classRouter } from '../modules/classes/classes.routes';
import { dashboardRouter } from '../modules/dashboard/dashboard.routes';
import { examRouter } from '../modules/exams/exams.routes';
import { expenseRouter } from '../modules/expenses/expenses.routes';
import { familyRouter } from '../modules/families/families.routes';
import { financeRouter } from '../modules/finance/finance.routes';
import { languageSettingRouter } from '../modules/language-settings/language-settings.routes';
import { notificationRouter } from '../modules/notifications/notifications.routes';
import { paymentRouter } from '../modules/payments/payments.routes';
import { permissionsRouter } from '../modules/permissions/permissions.routes';
import { reportRouter } from '../modules/reports/reports.routes';
import { resultRouter } from '../modules/results/results.routes';
import { roleRouter } from '../modules/roles/roles.routes';
import { studentRouter } from '../modules/students/students.routes';
import { subjectRouter } from '../modules/subjects/subjects.routes';
import { teacherRouter } from '../modules/teachers/teachers.routes';
import { userRouter } from '../modules/users/users.routes';

export const apiRouter = Router();

apiRouter.use('/auth', authRouter);
apiRouter.use('/users', userRouter);
apiRouter.use('/branches', branchRouter);
apiRouter.use('/students', studentRouter);
apiRouter.use('/teachers', teacherRouter);
apiRouter.use('/classes', classRouter);
apiRouter.use('/subjects', subjectRouter);
apiRouter.use('/attendance', attendanceRouter);
apiRouter.use('/exams', examRouter);
apiRouter.use('/results', resultRouter);
apiRouter.use('/payments', paymentRouter);
apiRouter.use('/finance', financeRouter);
apiRouter.use('/expenses', expenseRouter);
apiRouter.use('/families', familyRouter);
apiRouter.use('/books', bookRouter);
apiRouter.use('/audit', auditRouter);
apiRouter.use('/notifications', notificationRouter);
apiRouter.use('/roles', roleRouter);
apiRouter.use('/permissions', permissionsRouter);
apiRouter.use('/dashboard', dashboardRouter);
apiRouter.use('/reports', reportRouter);
apiRouter.use('/language-settings', languageSettingRouter);
apiRouter.use('/admin', adminRouter);
