export const enterpriseRoles = [
  'super_admin',
  'admin',
  'teacher',
  'student',
  'parent',
  'owner',
  'branch_manager',
  'system_automation'
] as const;

export const legacyRoleAliases = {
  family_student: 'parent',
  family: 'parent',
  accountant: 'admin',
  librarian: 'branch_manager',
  user: 'student'
} as const;

export type CanonicalRole = typeof enterpriseRoles[number];
export type LegacyRole = keyof typeof legacyRoleAliases;
export type SupportedRole = CanonicalRole | LegacyRole;

export const enterprisePermissions = [
  'DASHBOARD_VIEW',
  'USER_CREATE',
  'USER_VIEW',
  'USER_UPDATE',
  'USER_ACTIVATE',
  'USER_DEACTIVATE',
  'USER_DELETE',
  'ROLE_VIEW',
  'ROLE_MANAGE',
  'PERMISSION_VIEW',
  'PERMISSION_MANAGE',
  'BRANCH_CREATE',
  'BRANCH_VIEW',
  'BRANCH_UPDATE',
  'BRANCH_DELETE_REQUEST',
  'BRANCH_DELETE_APPROVE',
  'STUDENT_REGISTER',
  'STUDENT_VIEW',
  'STUDENT_UPDATE',
  'STUDENT_ASSIGN_CLASS',
  'STUDENT_SUSPEND',
  'TEACHER_REGISTER',
  'TEACHER_VIEW',
  'TEACHER_UPDATE',
  'TEACHER_ASSIGN_SUBJECT',
  'TEACHER_ASSIGN_CLASS',
  'TEACHER_PAYROLL_VIEW',
  'CLASS_CREATE',
  'CLASS_VIEW',
  'CLASS_UPDATE',
  'CLASS_DELETE',
  'SUBJECT_CREATE',
  'SUBJECT_VIEW',
  'SUBJECT_UPDATE',
  'ENROLLMENT_CREATE',
  'ENROLLMENT_VIEW',
  'ENROLLMENT_UPDATE',
  'ATTENDANCE_MARK',
  'ATTENDANCE_VIEW',
  'ATTENDANCE_POLICY_UPDATE',
  'EXAM_CREATE',
  'EXAM_VIEW',
  'EXAM_UPDATE',
  'EXAM_GRADE',
  'EXAM_PUBLISH',
  'QUESTION_CREATE',
  'QUESTION_VIEW',
  'QUESTION_UPDATE',
  'RESULT_CREATE',
  'RESULT_VIEW',
  'RESULT_PUBLISH',
  'PAYMENT_CREATE',
  'PAYMENT_VIEW',
  'PAYMENT_AUDIT',
  'SALARY_VIEW',
  'SALARY_MANAGE',
  'SALARY_AUDIT',
  'EXPENSE_CREATE',
  'EXPENSE_VIEW',
  'EXPENSE_AUDIT',
  'STATIONERY_SALE_CREATE',
  'STATIONERY_SALE_VIEW',
  'ANNOUNCEMENT_CREATE',
  'ANNOUNCEMENT_VIEW',
  'NOTIFICATION_CREATE',
  'NOTIFICATION_VIEW',
  'ADVERTISEMENT_CREATE',
  'ADVERTISEMENT_VIEW',
  'RESOURCE_CREATE',
  'RESOURCE_VIEW',
  'RESOURCE_UPDATE',
  'FAMILY_LINK_CREATE',
  'FAMILY_LINK_VIEW',
  'QR_CONTACT_CREATE',
  'QR_CONTACT_VIEW',
  'SESSION_VIEW',
  'SESSION_MANAGE',
  'REPORT_VIEW',
  'REPORT_EXPORT',
  'REPORT_GENERATE',
  'LANGUAGE_SETTING_UPDATE',
  'POLICY_UPDATE',
  'SYSTEM_RULE_UPDATE',
  'AUDIT_VIEW'
] as const;

export type PermissionKey = typeof enterprisePermissions[number];

export const rolePermissionMatrix: Record<CanonicalRole, PermissionKey[] | ['*']> = {
  super_admin: ['*'],
  admin: [
    'DASHBOARD_VIEW',
    'USER_VIEW',
    'USER_UPDATE',
    'USER_ACTIVATE',
    'STUDENT_REGISTER',
    'STUDENT_VIEW',
    'STUDENT_UPDATE',
    'STUDENT_ASSIGN_CLASS',
    'STUDENT_SUSPEND',
    'TEACHER_REGISTER',
    'TEACHER_VIEW',
    'TEACHER_UPDATE',
    'TEACHER_ASSIGN_SUBJECT',
    'TEACHER_ASSIGN_CLASS',
    'CLASS_CREATE',
    'CLASS_VIEW',
    'CLASS_UPDATE',
    'SUBJECT_CREATE',
    'SUBJECT_VIEW',
    'SUBJECT_UPDATE',
    'ENROLLMENT_CREATE',
    'ENROLLMENT_VIEW',
    'ENROLLMENT_UPDATE',
    'ATTENDANCE_MARK',
    'ATTENDANCE_VIEW',
    'ATTENDANCE_POLICY_UPDATE',
    'EXAM_CREATE',
    'EXAM_VIEW',
    'EXAM_UPDATE',
    'EXAM_GRADE',
    'EXAM_PUBLISH',
    'QUESTION_CREATE',
    'QUESTION_VIEW',
    'QUESTION_UPDATE',
    'RESULT_CREATE',
    'RESULT_VIEW',
    'RESULT_PUBLISH',
    'PAYMENT_CREATE',
    'PAYMENT_VIEW',
    'SALARY_VIEW',
    'EXPENSE_CREATE',
    'EXPENSE_VIEW',
    'STATIONERY_SALE_CREATE',
    'STATIONERY_SALE_VIEW',
    'ANNOUNCEMENT_CREATE',
    'ANNOUNCEMENT_VIEW',
    'NOTIFICATION_CREATE',
    'NOTIFICATION_VIEW',
    'RESOURCE_CREATE',
    'RESOURCE_VIEW',
    'RESOURCE_UPDATE',
    'FAMILY_LINK_CREATE',
    'FAMILY_LINK_VIEW',
    'QR_CONTACT_CREATE',
    'QR_CONTACT_VIEW',
    'REPORT_VIEW',
    'REPORT_EXPORT',
    'LANGUAGE_SETTING_UPDATE'
  ],
  teacher: [
    'DASHBOARD_VIEW',
    'STUDENT_VIEW',
    'CLASS_VIEW',
    'SUBJECT_VIEW',
    'ATTENDANCE_MARK',
    'ATTENDANCE_VIEW',
    'EXAM_CREATE',
    'EXAM_VIEW',
    'EXAM_UPDATE',
    'EXAM_GRADE',
    'QUESTION_CREATE',
    'QUESTION_VIEW',
    'QUESTION_UPDATE',
    'RESULT_CREATE',
    'RESULT_VIEW',
    'ANNOUNCEMENT_VIEW',
    'NOTIFICATION_CREATE',
    'NOTIFICATION_VIEW',
    'RESOURCE_VIEW',
    'RESOURCE_UPDATE',
    'FAMILY_LINK_VIEW'
  ],
  student: [
    'DASHBOARD_VIEW',
    'ATTENDANCE_VIEW',
    'EXAM_VIEW',
    'RESULT_VIEW',
    'PAYMENT_VIEW',
    'ANNOUNCEMENT_VIEW',
    'NOTIFICATION_VIEW',
    'RESOURCE_VIEW',
    'QR_CONTACT_VIEW'
  ],
  parent: [
    'DASHBOARD_VIEW',
    'ATTENDANCE_VIEW',
    'EXAM_VIEW',
    'RESULT_VIEW',
    'PAYMENT_VIEW',
    'ANNOUNCEMENT_VIEW',
    'NOTIFICATION_VIEW',
    'RESOURCE_VIEW',
    'FAMILY_LINK_VIEW',
    'QR_CONTACT_VIEW'
  ],
  owner: [
    'DASHBOARD_VIEW',
    'BRANCH_VIEW',
    'PAYMENT_VIEW',
    'PAYMENT_AUDIT',
    'SALARY_VIEW',
    'SALARY_AUDIT',
    'EXPENSE_VIEW',
    'EXPENSE_AUDIT',
    'REPORT_VIEW',
    'REPORT_EXPORT',
    'POLICY_UPDATE',
    'SYSTEM_RULE_UPDATE',
    'AUDIT_VIEW',
    'SESSION_VIEW'
  ],
  branch_manager: [
    'DASHBOARD_VIEW',
    'BRANCH_VIEW',
    'BRANCH_UPDATE',
    'USER_VIEW',
    'STUDENT_REGISTER',
    'STUDENT_VIEW',
    'STUDENT_UPDATE',
    'STUDENT_ASSIGN_CLASS',
    'TEACHER_REGISTER',
    'TEACHER_VIEW',
    'TEACHER_UPDATE',
    'TEACHER_ASSIGN_SUBJECT',
    'TEACHER_ASSIGN_CLASS',
    'CLASS_CREATE',
    'CLASS_VIEW',
    'CLASS_UPDATE',
    'SUBJECT_CREATE',
    'SUBJECT_VIEW',
    'SUBJECT_UPDATE',
    'ENROLLMENT_CREATE',
    'ENROLLMENT_VIEW',
    'ENROLLMENT_UPDATE',
    'ATTENDANCE_MARK',
    'ATTENDANCE_VIEW',
    'EXAM_CREATE',
    'EXAM_VIEW',
    'EXAM_UPDATE',
    'EXAM_GRADE',
    'RESULT_CREATE',
    'RESULT_VIEW',
    'PAYMENT_CREATE',
    'PAYMENT_VIEW',
    'EXPENSE_CREATE',
    'EXPENSE_VIEW',
    'ANNOUNCEMENT_CREATE',
    'ANNOUNCEMENT_VIEW',
    'NOTIFICATION_CREATE',
    'NOTIFICATION_VIEW',
    'RESOURCE_CREATE',
    'RESOURCE_VIEW',
    'RESOURCE_UPDATE',
    'REPORT_VIEW'
  ],
  system_automation: [
    'ATTENDANCE_MARK',
    'ATTENDANCE_VIEW',
    'NOTIFICATION_CREATE',
    'REPORT_GENERATE',
    'SALARY_MANAGE',
    'PAYMENT_AUDIT',
    'EXPENSE_AUDIT',
    'SYSTEM_RULE_UPDATE',
    'AUDIT_VIEW'
  ]
};

export interface RoutePolicy {
  prefix: string;
  methods?: string[];
  public?: boolean;
  permissions?: PermissionKey[];
  roles?: SupportedRole[];
  branchScoped?: boolean;
  ownership?: 'self' | 'assigned' | 'branch' | 'assigned_or_self' | 'assigned_or_branch' | 'branch_or_self' | 'governance';
  auditAction?: string;
}

export const enterpriseRoutePolicies: RoutePolicy[] = [
  { prefix: '/api/auth/login', public: true },
  { prefix: '/api/auth/refresh', public: true },
  { prefix: '/api/auth/register/student', public: true },
  { prefix: '/api/auth/register/options', public: true },
  { prefix: '/api/auth/forgot-password', public: true },
  { prefix: '/api/auth/reset-password', public: true },
  { prefix: '/api/auth/email-verification/confirm', public: true },
  { prefix: '/api/auth/phone-verification/confirm', public: true },
  { prefix: '/api/notifications/public', public: true },
  { prefix: '/api/auth/profile', permissions: ['DASHBOARD_VIEW'], ownership: 'self' },
  { prefix: '/api/users', permissions: ['USER_VIEW'], auditAction: 'USER_ROUTE_ACCESS' },
  { prefix: '/api/teachers', permissions: ['TEACHER_VIEW'], branchScoped: true, ownership: 'branch_or_self' },
  { prefix: '/api/students', permissions: ['STUDENT_VIEW'], branchScoped: true, ownership: 'branch_or_self' },
  { prefix: '/api/classes', permissions: ['CLASS_VIEW'], branchScoped: true, ownership: 'assigned_or_branch' },
  { prefix: '/api/subjects', permissions: ['SUBJECT_VIEW'], branchScoped: true, ownership: 'assigned_or_branch' },
  { prefix: '/api/attendance/policies', permissions: ['ATTENDANCE_POLICY_UPDATE'], branchScoped: true, auditAction: 'ATTENDANCE_POLICY_ACCESS' },
  { prefix: '/api/attendance', methods: ['POST'], permissions: ['ATTENDANCE_MARK'], branchScoped: true, ownership: 'assigned_or_self', auditAction: 'ATTENDANCE_ACCESS' },
  { prefix: '/api/attendance', permissions: ['ATTENDANCE_VIEW'], branchScoped: true, ownership: 'assigned_or_self', auditAction: 'ATTENDANCE_ACCESS' },
  { prefix: '/api/exams', permissions: ['EXAM_VIEW'], branchScoped: true, ownership: 'assigned_or_branch' },
  { prefix: '/api/results', permissions: ['RESULT_VIEW'], branchScoped: true, ownership: 'assigned_or_self' },
  { prefix: '/api/payments', permissions: ['PAYMENT_VIEW'], branchScoped: true, ownership: 'branch_or_self', auditAction: 'PAYMENT_ACCESS' },
  { prefix: '/api/salaries', permissions: ['SALARY_VIEW'], branchScoped: true, auditAction: 'SALARY_ACCESS' },
  { prefix: '/api/expenses', permissions: ['EXPENSE_VIEW'], branchScoped: true, auditAction: 'EXPENSE_ACCESS' },
  { prefix: '/api/finance', permissions: ['PAYMENT_VIEW'], branchScoped: true, auditAction: 'FINANCE_ACCESS' },
  { prefix: '/api/reports', permissions: ['REPORT_VIEW'], ownership: 'governance', auditAction: 'REPORT_ACCESS' },
  { prefix: '/api/notifications', permissions: ['NOTIFICATION_VIEW'], ownership: 'self' },
  { prefix: '/api/announcements', permissions: ['ANNOUNCEMENT_VIEW'], branchScoped: true },
  { prefix: '/api/learning-resources', permissions: ['RESOURCE_VIEW'], ownership: 'assigned_or_self' },
  { prefix: '/api/advertisements', permissions: ['ADVERTISEMENT_VIEW'] },
  { prefix: '/api/branches', permissions: ['BRANCH_VIEW'], branchScoped: true },
  { prefix: '/api/dashboard', permissions: ['DASHBOARD_VIEW'], ownership: 'governance' },
  { prefix: '/api/audit', permissions: ['AUDIT_VIEW'], ownership: 'governance' },
  { prefix: '/api/roles', methods: ['POST', 'PUT', 'PATCH', 'DELETE'], permissions: ['ROLE_MANAGE'], ownership: 'governance' },
  { prefix: '/api/roles', permissions: ['ROLE_VIEW'], ownership: 'governance' },
  { prefix: '/api/permissions', permissions: ['PERMISSION_VIEW'], ownership: 'governance' },
  { prefix: '/api/language-settings', permissions: ['LANGUAGE_SETTING_UPDATE'], ownership: 'self' },
  { prefix: '/api/sessions', permissions: ['SESSION_VIEW'], ownership: 'self' }
];

export const systemDependencies = {
  backend: ['node.js', 'express', 'mongodb', 'mongoose', 'jsonwebtoken', 'bcryptjs', 'joi'],
  frontend: ['react', 'vite', 'tailwindcss', 'react-query', 'zustand', 'i18next', 'framer-motion', 'recharts'],
  security: ['helmet', 'cors', 'express-rate-limit', 'request-sanitization', 'refresh-token-rotation', 'audit-logging'],
  operational: ['offline-ready-pwa', 'multilingual-support', 'scheduled-jobs', 'soft-delete']
} as const;
